### PR TITLE
[WIP] Navigation view

### PR DESCRIPTION
**Pull request by Jay-o-Way**
Can't believe it. This is the third attempt and it doesn't even work!

HELP

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
@niels9001 or @cgaarden, I'm trying to use a Navigation by Tag, but the `Navigate` bit is not working. I looked at examples on MS Learn, too. It should be rather simple, but I just can't get this to work. 😭 Can you help me on my way? Thanks.

**Comment by cgaarden** [comment]
I unfortunately haven't used that api.

**Comment by Jay-o-Way** [comment]
I am now trying to use a solution (using `x:Name`, see below) based on [the example in WinUI Gallery](winui3gallery://item/NavigationView), but that breaks with an unhandled exception 🤯

```cs
    private void NavView_ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)
    {
        if (args.InvokedItemContainer != null)
        {
            Type pageType = typeof(GeneralPage); // default
            if (args.InvokedItem == GeneralItem)
            {
                pageType = typeof(GeneralPage);
            }
            else if (args.InvokedItem == BrowsersItem)
            {
                pageType = typeof(BrowsersPage);
            }
            else if (args.InvokedItem == RulesetsItem)
            {
                pageType = typeof(RulesetsPage);
            }
            else if (args.InvokedItem == AboutItem)
            {
                pageType = typeof(AboutPage);
            }

            ContentFrame.Navigate(pageType);
            //NavView_Navigate(typeof(navPageType), args.RecommendedNavigationTransitionInfo);
        }
    }
```

**Comment by niels9001** [comment]
@Jay-o-Way Have you tried the WinUI Gallery samples? That should include basic navigation.

You can use SelectionChanged OR ItemInvoked. Looks like you are mixing both.

Set a SelectionChanged event on the NavView in XAML, and set a Tag on each NavigationViewItem.

In code-behind you can add this to the SelectionChanged eventhandler:

Type selectedPage = ((NavigationViewItem)args.SelectedItem).Tag switch
                {
                    "Home" => typeof(HomePage),
                    "About" => typeof(AboutPage),
                    _ => typeof(HomePage),
                };

            NavFrame.Navigate(selectedPage);

**Comment by Jay-o-Way** [comment]
Hey @niels9001 thanks for the suggestion. I indeed have tried both the SelectionChanged and ItemInvoked approaches. Left the methods for both in the code. I have indeed used the WinUI Gallery examples and now also your snippet. Still it breaks. The problem must be in a different place, but I have no idea where to search and the debugger isn't giving me much info.
image

**Pull request closed without merging**
