### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by Jay-o-Way**
### App-wide

- **Mica** with **SystemThemeWatcher**! 🥳
  - Fails on Windows 10 🙁 WPF-UI issue → https://github.com/lepoco/wpfui/pull/1094
  - Look out for **v4.0** https://github.com/lepoco/wpfui/pull/1107
- **Icons** for the windows! 🥳
- Colors and styles
- Moved **Buttons** to the bottom (using a central Style)
- Using `xmlns:wpfui=` everywhere - no more `ui=`

### Browser window

image
image

- Using **TitleBar** - Minimize button functions the same
- Logical order: "input" followed by "actions"
- Using **TextBox**
  - Using **Placeholder**
  - No "Copy" or "Edit" needed and we have #119
- Using **Button** to display browsers: simplifies UI (transparent) and **Click** handling!

> [!IMPORTANT]
> Commented keybindings and number-watching keys

### Ruleset Manager

image

### Ruleset editor window

image

### Timed browser

image

### CODE REVIEW

**Comment by Jay-o-Way** [comment]
Can you help with the two "to-do" ?

**Comment by Jay-o-Way** [comment]
@U-C-S Okay, it's now functional, with some braking changes. As always: this is "my" style. Hope it helps!

**Comment by Jay-o-Way** [comment]
### Video

https://github.com/U-C-S/Hurl/assets/65828559/e8ccd265-9c7d-4186-a288-03848cee44b2

**Comment by Jay-o-Way** [comment]
Alternative idea:
image

**Comment by Jay-o-Way** [comment]
@U-C-S I know you're kind of busy, but I hope you have a bit of time soon. I've been working a while on this and I'm really proud of it now! I hope you like it!

Note: Keybindings can be added back later, but there are different possible methods for that.

**Comment by Jay-o-Way** [comment]
@niels9001 🔝 Look what I made! 😁

**Comment by Jay-o-Way** [comment]
Ahhhh it's so difficult to wait.. 😆

**Comment by riotrah** [comment]
Not that anyone asked, but thought I'd share my aesthetic 2 cents.

fwiw I personally really do not like Mica, so I'm hoping this PR (if it's used ultimately, and in general with this project otherwise) doesn't force it. I actually prefer the un-colored (sorta light grey/white-ish in light mode, dark grey in dark) background that some windows UI surfaces have, over Mica, with Acrylic above either. All three options might be nice actually if users want it and it's not hard to implement (meaning, add the uncolored one, as there's already Mica/Acrylic).

Apart from colors tho, I like everything else about your version. The consistency with the rest of Win11's design language really makes Hurl feel like a part of windows, which feels appropriate given it's a power user utility app - one of my favorite things about modern third party mac apps is how well they gel with the rest of the OS. This version feels a lot like, say, the "Open with..." dialog, or even the start menu, etc.

The only thing would be that I'd expect (going by Start Menu) that context menus and tooltips would have drop shadows. And something about the corner rounding and padding of the tooltip seems off.

**Comment by riotrah** [comment]
And if you guys were willing, I wanted to derail this thread for second to ask how I can learn more about the various different ways of making windows apps, eg what is the difference/tradeoffs between WPF, WinUI, etc?

**Comment by niels9001** [comment]
> And if you guys were willing, I wanted to derail this thread for second to ask how I can learn more about the various different ways of making windows apps, eg what is the difference/tradeoffs between WPF, WinUI, etc?

There was a recent Build session about that: https://youtu.be/ZjaL3pL-OuM?si=ZCPdRGEDB6JcQ6X6

**Comment by Jay-o-Way** [comment]
Hi @riotrah, thank you for your message!

Yeah, the background issue feels like a personal opinion. I don't mind it. But, of course, you may have yours 🙂 I will leave it to @U-C-S if he wants to use it or something else. Actually, with the current version of WPF-UI, there is a bug where, after a while, the mica effect fails. Even on Windows 11. So, you might just like that, haha!

Thank you so much for the compliment! I'm really proud of it! 😇 I even have a few more (small) things waiting for a next PR.

About the little UI bugs you mention: that's a WPF-UI issue. From what I can tell it is "just" a third-party framework and personally I am not a fan of that. I would rather use either WinUI c.q. Microsoft WPF. But that's also a choice @U-C-S has to make. And it requires quite a big re-write.

**Comment by U-C-S** [comment]
> I would rather use either WinUI

I really want to, But it's so hard/confusing to get a unpackaged app running properly and reliably, and the install sizes are huge (like ranging from 40MB to 180MB). Wouldn't be much Big rewrite either, I have done it thrice (including a UWP port) already at this point and gave up during publishing. But the preview updates for both WPF and WinAppSDK/WinUI looks really promising.

Looking into your PR currently @Jay-o-Way

**Comment by U-C-S** [comment]
Tried it out locally. 

I like couple of ideas here like the bottom bar where you put the Rules, settings btns... I personally do not like the way the looks of WinUI TextBox, But I want to do something like current Edit URL button which onClick gets swapped with TextBox control, which I feel is best of both our ideas. What do you think ?

I will keep updating this comment as I use it.

**Comment by Jay-o-Way** [comment]
> I personally do not like the way the looks of WinUI TextBox

Is there something specific? This control has a lot of important benefits with accessibility: Tabstop, in-place-editing, built-in "clear" button and context-menu, screen reader support... People that need to use non-standard input devices really would like this...
Adding a button for a pop-up adds a lot of interaction steps and users usually like things to be as fast and easy as possible.

Maybe I could set the default background to Tranparent - to make it even more subtle. That'll leave the _hover_ and _focus_ colors intact.

**Comment by Jay-o-Way** [comment]
P.S. next branch is already work in progress: https://github.com/Jay-o-Way/Hurl/tree/UI-improvements

**Comment by U-C-S** [comment]
> Maybe I could set the default background to Transparent - to make it even more subtle

It looks much better actually.
- Also wanting to use a btn changing into TextBox onClick, because Editing URL from within Hurl window which I believe is a rare interaction and Clear current URL could be a btn itself beside it.

Additionally, continue with my thoughts on changes you made, 
- continuing from above statement about the URL TextBox being a btn, I prefer it would be on the bottom of the browsers grid component. Just so it's not the main focus but another feature.
- like the changes made for Timed default and ruleset manager windows overall
- but not with the Ruleset Editor window, and Type and Window card specifically. The 'Add' btn feels separate from the function meant by the card itself. Would include btn inside the card itself 
- Also the info btn, which is missing from above point, is just a small explanation flyout I want to include onClick about different Types of rules.

I want to continue further (including about the change I made recently: https://github.com/U-C-S/Hurl/commit/13e3d4d79d65e388e952b570c91392ddc3c5720b#commitcomment-143173677), but Maybe at this point, it would be a better idea, to have it in a new discussion conversation instead because it feels UI design discussions are spread out in lots of places.

> Typing this from mobile and from memory...:)

**Comment by Jay-o-Way** [comment]
> Maybe at this point, it would be a better idea, to have it in a new discussion conversation

Let's use https://github.com/U-C-S/Hurl/discussions/131 then

**Comment by Jay-o-Way** [comment]
@U-C-S I Updated **TextBox** and **Add** button. I know the Textboxt is an open discussion (literally) but is there anything actually blocking this? Thanks.

**Comment by U-C-S** [comment]
Sorry, didn't notice this comment

> anything actually blocking this?

PR tweaks lot of things, which is fine, but there are changes I don't want or have a prior focused discussion... which would make a quite a list. So probably I think, the better idea would be breaking this PR into **multiple small PRs** where I have some I can merge straight away (like the code refactor stuff etc...), some I don't like to (removal of 2 app visual settings etc...) and some with discussion.

honestly I am not certain what's the better thing to do here for this PR. or Should I review this PR and just point out things I wouldn't want ?

**Comment by Jay-o-Way** [comment]
Okay. I hear you.

**Comment by U-C-S** [comment]
> multiple PRs will create merge conflicts between them, causing extra work

Yeah you are right. But don't know any alternative way we can do this, but more focused PRs are very sensible to keep track off for me as a maintainer.

> Also, I saw you have a few different branches. Which one would be the best to use

`main` branch is fine....

**Comment by Jay-o-Way** [comment]
> Yeah you are right. But don't know any alternative way we can do this, but more focused PRs are very sensible to keep track off for me as a maintainer.

I understand. (Not the first time I got that feedback 🫣)
I think the GitHub Merge Que will help. But I have no personal experience with it yet...

**Pull request closed without merging**
